language: node_js
node_js:
- '5.0'
cache:
  directories:
  - node_modules
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- npm install
script:
- npm run lint
- npm run test
- NODE_ENV=production npm run dist
after_success:
- npm run codecov
- ./deploy.sh

env:
  global:
  - secure: TWkQS8R0xFenldKdPZZLvbu8KmzSI8+ZbZQExzHk5m5ZFjcEE6D0AwFP4ScICJZ4/PwbB8yGT35WwfYlaxjAbU0HNAP6PijP+4G0sO2DUhenyZZcVF/O8V+uKNARIT56oucoTaoA1uwQSOuX1UniGHA+EflaGAAbmney4ottESvx+ez2FTUxOJ9pJBNDJv9Eo9hq1zFfBw6PwAyceJNmpXxoXmm8Z9ON7CpICMHDm2H2qmN8y51x9oHirvg8bzWJiTK+JpjQXoFYyAPtOQH2UwGt4/wzS5tcoTFSsTA5uzkT0+kPBJB2Z4vmJ07nl/jynw99qpfvPxvInNMBFxtXlZWARFne1TU7KcXYV5vCc0db1atCaveKovQjI9D1SnVeXCTwft8E7uJcJbibTp1lpUcw+JS2vErtoXY1ZZzAXkOsT8azsIIXIcevKw47SC7giI0P5Dsgu+VXZ7Aln07TocnHpBIEg7Ik66cBhYS2m0vRxRj1Jz2SRmdW6Y/mraYhnKij/0AimmYGRXH0uNFgTGd7kjMu+V+Rnb8P91zM2WyCRRt5l5KVL3nllXbtGiAWuJthhknrQKRGYnuntcpaUBkzRCErE5gPf+TsOB39vVuCGbiqdI0ioD+mql5TE4p7NXnwsSKwkP7dU1hNfICCu+0O7GYBJoLpVoc/yxVHUag=
  - secure: lIvmRMVuLdjcjQxmOmcPX7Au/s67itfaSH4KeuRKZGT8uHuiN7cz6AQReaWn9SKdstekPCjuOrlYhPY/9r1SaNq+LmPYiTfpCEVkbLZ1+xOLJyy6TwXWkFzq1GJCppNtgL3IWOh9/BQlhJMw6VRQNppc3sYsFDobIVCkcYsARLIBCLybYdlQ2TmC+yuLg7q1ZPQqUA3nMGfo1LvKTMI/icErdLwD3b94sde6Y7SsYUITiv7PqMWJETpi0u8NUHwWTIw32ZDbKqanorMzxiOZExp3GMRr4BHT5AO2oSH3w6gt+TNuVoKLlItYU5vPOwHP9MFxjGpPqSsGIvBILDflNH13dRFZqR2EEjc7sJLpc6dj/oMI084vMKBotEoaz+iCoVtE44uh6KdyjuRl8ggJLEe+FocG4jxS4UhUuQbeQyexV/tjKP3D6/aiLEl6vX1IAJz+VzPGlZPBUpIyeXpxYQTEVFfHGzQ8iHHRRdF1jr1+zq6NEC3uLn2Zfzr2IV/9ItQRMiz8Zvp3FwaMNmtiT3kFuK94ibMCWk9BzrsbNOQaUuYOcVCmtt3VnN6U/35bydiiFbzdsxfd3dtGNVuI2aAFbJ2yNtyfrhnscwag5aQRQdnuLqAsng4x+Go58eEHOU0jR/njlgnIpbwxhyr0uB2L0fvYT5v3Dn5y0RV6dWg=
