AWSTemplateFormatVersion: '2010-09-09'
Description: Template for sportnumerics explorer
Parameters:
  StageParameter:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prodgreen
    - prodblue
    Description: Stage to deploy
Mappings:
  StageMapping:
    dev:
      aliases:
      - staging.dev.sportnumerics.com
      certificate: arn:aws:acm:us-east-1:265978616089:certificate/8a8d8c31-20b3-49c4-8b58-13b259064cc6
    prod:
      aliases:
      - staging.sportnumerics.com
      certificate: arn:aws:acm:us-east-1:265978616089:certificate/7140c26c-5b35-4f21-b16d-695bf5a659e6
Conditions:
  CreateStagingDistribution:
    Fn::Not:
      - Fn::Equals:
        - Ref: StageParameter
        - dev
Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName:
        Fn::Join:
        - "-"
        - - sportnumerics-explorer
          - Ref: StageParameter
  StagingCloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: CreateStagingDistribution
    Properties:
      DistributionConfig:
        Aliases:
          Fn::FindInMap:
          - StageMapping
          - Ref: StageParameter
          - aliases
        CustomErrorResponses:
        - ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: "/index.html"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: DefaultOrigin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        DefaultRootObject: index.html
        Enabled: true
        Origins:
        - DomainName:
            Fn::Join:
            - "."
            - - Fn::Join:
                - "-"
                - - sportnumerics-explorer
                  - Ref: StageParameter
              - s3.amazonaws.com
          Id: DefaultOrigin
          S3OriginConfig: {}
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn:
            Fn::FindInMap:
              - StageMapping
              - Ref: StageParameter
              - certificate
          SslSupportMethod: sni-only
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DeploymentBucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: s3:GetObject
          Principal: "*"
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: DeploymentBucket
              - "/*"
Outputs:
  CloudfrontArn:
    Description: Staging cloudfront distribution for sportnumerics frontend
    Value:
      Fn::If:
        - CreateStagingDistribution
        - Ref: StagingCloudfrontDistribution
        - "DistributionNotCreated"
