AWSTemplateFormatVersion: '2010-09-09'
Description: Template for sportnumerics explorer
Parameters:
  StageParameter:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
    Description: Stage to deploy
Mappings:
  StageToAliasMap:
    dev:
      aliases:
      - dev.sportnumerics.com
    prod:
      aliases:
      - sportnumerics.com
      - www.sportnumerics.com
      - prod.sportnumerics.com
Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName:
        Fn::Join:
        - "-"
        - - sportnumerics-explorer
          - Ref: StageParameter
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          Fn::FindInMap:
          - StageToAliasMap
          - Ref: StageParameter
          - aliases
        CustomErrorResponses:
        - ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: "/index.html"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: DefaultOrigin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        DefaultRootObject: index.html
        Enabled: true
        Origins:
        - DomainName:
            Fn::Join:
            - "."
            - - Fn::Join:
                - "-"
                - - sportnumerics-explorer
                  - Ref: StageParameter
              - s3.amazonaws.com
          Id: DefaultOrigin
          S3OriginConfig: {}
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:265978616089:certificate/198f3e8e-17ff-4da7-bca3-d5f42f473ee7
          SslSupportMethod: sni-only
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DeploymentBucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: s3:GetObject
          Principal: "*"
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: DeploymentBucket
              - "/*"
Outputs:
  CloudfrontArn:
    Description: Cloudfront distribution for sportnumerics frontend
    Value:
      Ref: CloudfrontDistribution
