FROM alpine:3.4

WORKDIR /work

RUN apk add --no-cache bash curl git docker py-pip openssl nodejs build-base

RUN pip install --upgrade pip

RUN pip install --upgrade awscli

ADD package.json npm-shrinkwrap.json ./

ADD . .

CMD npm install && npm run dist && ./deploy.sh
