FROM node:alpine

WORKDIR /work

RUN apk add --no-cache bash curl git py-pip openssl alpine-sdk

RUN pip install --upgrade pip

RUN pip install --upgrade awscli

ADD package.json yarn.lock ./

RUN yarn

ADD . ./

CMD ./deploy.sh
