FROM node:alpine

WORKDIR /work

RUN apk add --no-cache py-pip git

RUN pip install --upgrade pip

RUN pip install --upgrade awscli

ADD package.json yarn.lock ./

RUN yarn

ADD . ./

CMD ./deploy.sh
